walabotapi/devices/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, ValidationError
from walabotapi.models import User, Device



class DeviceForm(FlaskForm):
  device_id = StringField('Device ID', validators=[DataRequired()])
  patient_name = StringField('Patient Name', validators=[DataRequired()])
  location = TextAreaField('Location Description', validators=[DataRequired()])
  submit = SubmitField('Register')

  def validate_device_id(self, device_id):
    device = Device.query.filter_by(device_id=device_id.data).first()
    if device:
      raise ValidationError('That device ID has already been registered. Please register another device.')

walabotapi/devices/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from walabotapi import db
from walabotapi.models import Device, Fall, Presence, Status, Fallback
from walabotapi.devices.forms import DeviceForm



devices = Blueprint('devices', __name__)


@devices.route('/device/manage', methods=['GET', 'POST'])
@login_required
def manage_devices():
    form = DeviceForm()
    devices = Device.query.filter_by(owner=current_user).all()
    if form.validate_on_submit():
        device = Device(device_id=form.device_id.data, patient_name=form.patient_name.data, location=form.location.data, owner=current_user)
        db.session.add(device)
        db.session.commit()
        flash('Your device has been successfully registered', 'success')
        return redirect(url_for('devices.manage_devices'))
    return render_template('manage_devices.html', title='Manage Devices', form=form, devices=devices)


@devices.route('/device/manage/<int:device_db_id>')
@login_required
def delete_device(device_db_id):
    device = Device.query.get_or_404(device_db_id)
    if device.owner != current_user:
        abort(403)
    db.session.delete(device)
    db.session.commit()
    return redirect(url_for('devices.manage_devices'))


@devices.route('/devices')
@login_required
def devices_view():
    devices_list = Device.query.filter_by(owner=current_user).all()
    return render_template('devices.html', title='Registered Devices', devices=devices_list)


@devices.route('/device/falls/<string:device_id>')
@login_required
def fall(device_id):
    device = Device.query.filter_by(device_id=device_id).first_or_404()
    if device.owner != current_user:
        abort(403)
    page = request.args.get('page', 1, type=int)
    falls = Fall.query.filter_by(device_id=device_id).order_by(Fall.id.desc()).paginate(page=page, per_page=5)
    return render_template('events_fall.html', title='Fall Events', falls=falls, device_id=device_id, device= device)


@devices.route('/device/falls/manage/<int:fall_db_id>')
@login_required
def delete_fall(fall_db_id):
    device_id = request.args.get('device_id')
    device = Device.query.filter_by(device_id=device_id).first_or_404()
    if device.owner != current_user:
        abort(403)
    fall = Fall.query.get_or_404(fall_db_id)
    db.session.delete(fall)
    db.session.commit()
    return redirect(url_for('devices.fall', device_id=device_id))


@devices.route('/device/presences/<string:device_id>')
@login_required
def presence(device_id):
    device = Device.query.filter_by(device_id=device_id).first_or_404()
    if device.owner != current_user:
        abort(403)
    page = request.args.get('page', 1, type=int)
    presences = Presence.query.filter_by(device_id=device_id).order_by(Presence.id.desc()).paginate(page=page, per_page=5)
    return render_template('events_presence.html', title='Presence Events', presences=presences, device_id=device_id, device= device)


@devices.route('/device/presences/manage/<int:presence_db_id>')
@login_required
def delete_presence(presence_db_id):
    device_id = request.args.get('device_id')
    device = Device.query.filter_by(device_id=device_id).first_or_404()
    if device.owner != current_user:
        abort(403)
    presence = Presence.query.get_or_404(presence_db_id)
    db.session.delete(presence)
    db.session.commit()
    return redirect(url_for('devices.presence', device_id=device_id))


@devices.route('/device/statuses/<string:device_id>')
@login_required
def status(device_id):
    device = Device.query.filter_by(device_id=device_id).first_or_404()
    if device.owner != current_user:
        abort(403)
    page = request.args.get('page', 1, type=int)
    statuses = Status.query.filter_by(device_id=device_id).order_by(Status.id.desc()).paginate(page=page, per_page=5)
    return render_template('events_status.html', title='Status Events', statuses=statuses, device_id=device_id, device= device)


@devices.route('/device/statuses/manage/<int:status_db_id>')
@login_required
def delete_status(status_db_id):
    device_id = request.args.get('device_id')
    device = Device.query.filter_by(device_id=device_id).first_or_404()
    if device.owner != current_user:
        abort(403)
    status = Status.query.get_or_404(status_db_id)
    db.session.delete(status)
    db.session.commit()
    return redirect(url_for('devices.status', device_id=device_id))


@devices.route('/device/fallback')
@login_required
def fallback():
    page = request.args.get('page', 1, type=int)
    fallbacks = Fallback.query.order_by(Fallback.id.desc()).paginate(page=page, per_page=5)
    return render_template('events_fallback.html', title='Fallback Data', fallbacks=fallbacks)


@devices.route('/device/fallback/manage/<int:fallback_db_id>')
@login_required
def delete_fallback(fallback_db_id):
    fallback = Fallback.query.get_or_404(fallback_db_id)
    db.session.delete(fallback)
    db.session.commit()
    return redirect(url_for('devices.fallback'))

walabotapi/main/routes.py
from flask import render_template, Blueprint


main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    return render_template('home.html', title='Home')

@main.route('/about')
def about():
    return render_template('about.html', title='About')

walabotapi/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from walabotapi import db, bcrypt
from walabotapi.models import User
from walabotapi.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from walabotapi.users.utils import send_reset_email

users = Blueprint('users', __name__)



@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        flash(f'You are already logged in as {current_user.username}', 'warning')
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash(f'You are already logged in as {current_user.username}', 'warning')
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash(f'Login Sucessful, {current_user.username}', 'success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['POST', 'GET'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been successfully updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', title='Account', form=form)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        flash(f'You are already logged in as {current_user.username}', 'warning')
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email with instructions to reset your password has been sent to your email address', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        flash(f'You are already logged in as {current_user.username}', 'warning')
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

walabotapi/templates/about.html
{% extends "layout.html" %} 
{% block content%}
  <h1>About Page</h1>
  <p>This API was developed in 2020 by Duly Stichmann for Bethesda Waters. All rights reserved.</p>
  <br>
  <footer><small>&COPY 2020 Duly Stichmann</small></footer>
{% endblock content%}

walabotapi/templates/account.html
{% extends "layout.html" %} 
{% block content%}
  <div class="content-section">
    <div class="media">
      <div class="media-body">
        <h2 class="account-heading">{{current_user.username}}</h2>
        <p class="text-secondary">{{current_user.email}}</p>
      </div>
    </div>
      <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Manage Account</legend>
          <div class="form-group">
            {{ form.username.label(class="form-control-label") }}
            {% if form.username.errors %}
            {{form.username(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.username.errors %}
              <span>{{ error}}</span>
              {% endfor %}
            </div>
            {% else %}
            {{form.username(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
            {{form.email(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
              <span>{{ error}}</span>
              {% endfor %}
            </div>
            {% else %}
            {{form.email(class="form-control form-control-lg") }}
            {% endif %}
          </div>
        </fieldset>
        <div class="form-group">
          {{ form.submit(class="btn btn-outline-info") }}
        </div>
      </form>
  </div>
{% endblock content%}

walabotapi/templates/devices.html
{% extends "layout.html" %}
{% block content %}
{% for device in devices %}
  <div class="content-section">
    <legend class="border-bottom mb-4">Registered Devices</legend>
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <span class="mr-2">{{ device.owner.username }}</span>
          <small class="text-muted">{{ device.device_id }}</small>
        </div>
        <span class="device-link">
          <a class="btn btn-secondary btn-sm" href="{{ url_for('devices.fall', device_id=device.device_id) }}">Falls</a>
        </span>
        <span class="device-link">
          <a class="btn btn-secondary btn-sm" href="{{ url_for('devices.status', device_id=device.device_id) }}">Statuses</a>
        </span>
        <span class="device-link">
          <a class="btn btn-secondary btn-sm" href="{{ url_for('devices.presence', device_id=device.device_id) }}">Presences</a>
        </span>
        <h2>{{ device.patient_name }}</h2>
        <p class="article-content">{{ device.location }}</p>
      </div>
    </article>
  </div>
{% endfor %}
{% endblock content %}

walabotapi/templates/events_fall.html
{% extends "layout.html" %} 
{% block content%}
  <div class="content-section">
    <legend class="border-bottom mb-4">Fall Events for {{ device.patient_name }} ({{ falls.total }})</legend>
    {% for fall in falls.items %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <span class="mr-2">{{ fall.timestamp_str }}</span>
          <small class="text-muted">{{ fall.event_id }}</small>
        </div>
        <span class="device-link"><a class="btn btn-secondary btn-danger btn-sm"
            href="{{ url_for('devices.delete_fall', fall_db_id=fall.id, device_id=fall.device_id) }}">Delete fall</a></span>
        <h2><a class="article-title"
            href="#">{{ fall.type_ }}</a></h2>
        <p class="article-content">{{ fall.status }}</p>
      </div>
    </article>
    {% endfor %}
    {% for page_num in falls.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if falls.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('devices.fall', device_id=device_id, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('devices.fall', device_id=device_id, page=page_num) }}">{{ page_num }}</a>
        {%endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  </div>
{% endblock content %}

walabotapi/templates/events_fallback.html
{% extends "layout.html" %}
{% block content%}
<div class="content-section">
  <legend class="border-bottom mb-4">Fallback Events ({{ fallbacks.total }})</legend>
  {% for fallback in fallbacks.items %}
  <article class="media content-section">
    <div class="media-body">
      <span class="device-link"><a class="btn btn-secondary btn-danger btn-sm"
          href="{{ url_for('devices.delete_fallback', fallback_db_id=fallback.id) }}">Delete post</a></span>
      <h3>{{fallback.origin}}</h3>
      <p class="article-content">{{ fallback.payload_string }}</p>
    </div>
  </article>
  {% endfor %}
  {% for page_num in fallbacks.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
  {% if fallbacks.page == page_num %}
  <a class="btn btn-info mb-4"
    href="{{ url_for('devices.fallback', page=page_num) }}">{{ page_num }}</a>
  {% else %}
  <a class="btn btn-outline-info mb-4"
    href="{{ url_for('devices.fallback', page=page_num) }}">{{ page_num }}</a>
  {%endif %}
  {% else %}
  ...
  {% endif %}
  {% endfor %}
</div>
{% endblock content %}

walabotapi/templates/events_presence.html
{% extends "layout.html" %} 
{% block content%}
  <div class="content-section">
    <legend class="border-bottom mb-4">Presence Events for {{ device.patient_name }} ({{ presences.total }})</legend>
    {% for presence in presences.items %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <span class="mr-2">{{ presence.timestamp }}</span>
          <small class="text-muted">{{ presence.device_id }}</small>
        </div>
        <span class="device-link"><a class="btn btn-secondary btn-danger btn-sm"
            href="{{ url_for('devices.delete_presence', presence_db_id=presence.id, device_id=presence.device_id) }}">Delete presence</a></span>
        <h2><a class="article-title" href="#">{{ presence.presence_detected }}</a></h2>
        <p class="article-content">{{ presence.presence_region_map }}</p>
      </div>
    </article>
    {% endfor %}
    {% for page_num in presences.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if presences.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('devices.presence', device_id=device_id, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('devices.presence', device_id=device_id, page=page_num) }}">{{ page_num }}</a>
        {%endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  </div>
{% endblock content %}

walabotapi/templates/events_status.html
{% extends "layout.html" %} 
{% block content%}
  <div class="content-section">
    <legend class="border-bottom mb-4">Status Events for {{ device.patient_name }} ({{ statuses.total }})</legend>
    {% for status in statuses.items %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <span class="mr-2">{{ status.timestamp }}</span>
          <small class="text-muted">{{ status.up_time }}</small>
        </div>
        <span class="device-link"><a class="btn btn-secondary btn-danger btn-sm"
            href="{{ url_for('devices.delete_status', status_db_id=status.id, device_id=status.device_id) }}">Delete status</a></span>
        <h2><a class="article-title" href="#">{{ status.status }}</a></h2>
        <p class="article-content">{{ status.wifi_state }}</p>
      </div>
    </article>
    {% endfor %}
    {% for page_num in statuses.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if statuses.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('devices.status', device_id=device_id, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('devices.status', device_id=device_id, page=page_num) }}">{{ page_num }}</a>
        {%endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  </div>
{% endblock content %}

walabotapi/templates/home.html
{% extends "layout.html" %}
{% block content %}
  <h1>Home of the Walabot&TRADE; device API</h1>
  <p>This interactive website can be used to view alert messages sent by your Walabot&TRADE; device. Alert messages include Fall events, presence detection, and also device status updates. Users can add device access to their accounts by registering a device by its ID number found on the back of the unit and the patient name associated with the device. Create a user login to get started.</p>
{% endblock content %}

walabotapi/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags from bootstrap-->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
    <title>Walabot API - {{ title }}</title>
    {% else %}
    <title>Walabot API</title>
    {% endif %}
  </head>
  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Walabot Dashboard</a>
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarToggle"
            aria-controls="navbarToggle"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('devices.devices_view') }}">Device Daskboard</a>
                <a class="nav-item nav-link" href="{{ url_for('devices.manage_devices') }}">Manage Devices</a>
                <a class="nav-item nav-link" href="{{ url_for('devices.fallback') }}">Fallback Data</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Manage Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout {{current_user.username}}</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category}}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <!-- <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
            <ul class="list-group">
              <li class="list-group-item list-group-item-light">Latest Posts</li>
              <li class="list-group-item list-group-item-light">Announcements</li>
              <li class="list-group-item list-group-item-light">Calendars</li>
              <li class="list-group-item list-group-item-light">etc</li>
            </ul>
            </p>
          </div>
        </div> -->
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

walabotapi/templates/login.html
{% extends "layout.html" %} 
{% block content%}
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Log In</legend>
        <div class="form-group">
          {{ form.email.label(class="form-control-label") }}
          {% if form.email.errors %}
            {{form.email(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
              <span>{{ error}}</span>
              {% endfor %}
            </div>
          {% else %}
            {{form.email(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.password.label(class="form-control-label") }}
          {% if form.password.errors %}
            {{form.password(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}
              <span>{{ error}}</span>
              {% endfor %}
            </div>
          {% else %}
            {{form.password(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-check">
          {{ form.remember(class="form-check-input") }}
          {{ form.remember.label(class="form-check-label") }}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
      <small class="text-muted ml-2">
        <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
      </small>
    </form>
  </div>
  <div class="border-top pt-3">
    <small class="text-muted">
      Need An Account?
      <a href="{{ url_for('users.register') }}" class="ml-2">Register Now</a>
    </small>
  </div>
{% endblock content%}

walabotapi/templates/manage_devices.html
{% extends "layout.html" %} 
{% block content%}
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Add A Device</legend>
        <div class="form-group">
          {{ form.device_id.label(class="form-control-label") }}
          {% if form.device_id.errors %}
          {{form.device_id(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.device_id.errors %}
            <span>{{ error}}</span>
            {% endfor %}
          </div>
          {% else %}
          {{form.device_id(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.patient_name.label(class="form-control-label") }}
          {% if form.patient_name.errors %}
          {{form.patient_name(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.patient_name.errors %}
            <span>{{ error}}</span>
            {% endfor %}
          </div>
          {% else %}
          {{form.patient_name(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.location.label(class="form-control-label") }}
          {% if form.location.errors %}
          {{form.location(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.location.errors %}
            <span>{{ error}}</span>
            {% endfor %}
          </div>
          {% else %}
          {{form.location(class="form-control form-control-lg") }}
          {% endif %}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
    </form>
  </div>
  <div class="content-section">
    <legend class="border-bottom mb-4">Delete A Device</legend>
      {% for device in devices %}
      <article class="media content-section">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('devices.devices_view') }}">{{ device.owner.username }}</a>
            <small class="text-muted">{{ device.device_id }}</small>
          </div>
          <span class="device-link"><a class="btn btn-secondary btn-danger btn-sm"
              href="{{ url_for('devices.delete_device', device_db_id=device.id) }}">Delete device</a></span>
          <h2 >{{ device.patient_name }}</h2> 
          <p class="article-content">{{ device.location }}</p>
        </div>
      </article>
      {% endfor %}
  </div>
{% endblock content%}

walabotapi/templates/reset_request.html
{% extends "layout.html" %}
{% block content%}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Reset Password</legend>
      <div class="form-group">
        {{ form.email.label(class="form-control-label") }}
        {% if form.email.errors %}
        {{form.email(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{ error}}</span>
          {% endfor %}
        </div>
        {% else %}
        {{form.email(class="form-control form-control-lg") }}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content%}